manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    # petejohanson is the DEV of ZMK - need his drivers for Cirque
    - name: petejohanson
      url-base: https://github.com/petejohanson
    #pm0u refrences pete for the cirque trackpad - thing these are required to make it work
    - name: pm0u
      url-base: https://github.com/pm0u
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    ### below is the modules that are needed for the CIRQUE 40mm Trackpad
    #Pete is a ZMK dev, these are the drivers to make the cirque work
    - name: cirque-input-module
      remote: petejohanson
      revision: main
    #pm0u cirque section that uses pete - needed for the cirque to work
    - name: glidepoint_i2c
      remote: pm0u
      revision: main
      path: modules/glidepoint_i2c
  self:
    path: config
